name: CI/CD - Docker para AWS ECR

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-2
      ECR_REPOSITORY: ${ { secrets.ECR_REPOSITORY }}
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup do PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      - name: Instalar dependências PHP
        run: composer install --no-interaction --prefer-dist --optimize-autoloader
        
      - name: Dar permissão ao PHPUnit
        run: chmod +x vendor/bin/phpunit

      - name: Rodar testes com PHPUnit
        run: composer test

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${ { secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${ { secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login no Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Construir imagem Docker
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REPOSITORY:$IMAGE_TAG $aws-access-key-id.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Fazer push para o Amazon ECR
        run: |
          docker push $aws-access-key-id.dkr.ecr.$ECR_REPOSITORY.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
      - name: Update ECS Service
        run:
          aws ecs update-service \
          --cluster ci-cd-nuvem-cl \
          --service ci-cd-nuvem-td-service-jiq9o3eb \
          --force-new-deployment